# syntax=docker/dockerfile:1.2
FROM python:3.9
# put you docker configuration here
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt
COPY ./requirements-dev.txt /code/requirements-dev.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements-dev.txt

# 
COPY ./ /code/

CMD ["make", "tests"]
